name: Vercel Deploy Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main

concurrency:
  group: deploy-production

jobs:
  deploy-production:
    name: Build and Deploy Production
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: ${{ steps.deploy-url.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > vercel-out.txt
      - name: Set Environment URL
        id: deploy-url
        if: ${{ success() }}
        run: echo "url=$(tail -n 1 vercel-out.txt)" >> $GITHUB_OUTPUT